/*
 * This file is generated by jOOQ.
 */
package com.logankulinski.jooq;


import com.logankulinski.jooq.tables.Issue;
import com.logankulinski.jooq.tables.Label;
import com.logankulinski.jooq.tables.Repository;
import com.logankulinski.jooq.tables.records.IssueRecord;
import com.logankulinski.jooq.tables.records.LabelRecord;
import com.logankulinski.jooq.tables.records.RepositoryRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<IssueRecord> ISSUE_PKEY = Internal.createUniqueKey(Issue.ISSUE, DSL.name("issue_pkey"), new TableField[] { Issue.ISSUE.ID }, true);
    public static final UniqueKey<LabelRecord> LABEL_PKEY = Internal.createUniqueKey(Label.LABEL, DSL.name("label_pkey"), new TableField[] { Label.LABEL.ID }, true);
    public static final UniqueKey<RepositoryRecord> REPOSITORY_PKEY = Internal.createUniqueKey(Repository.REPOSITORY, DSL.name("repository_pkey"), new TableField[] { Repository.REPOSITORY.ID }, true);
}
