/*
 * This file is generated by jOOQ.
 */
package com.logankulinski.jooq;


import com.logankulinski.jooq.tables.Issue;
import com.logankulinski.jooq.tables.Label;
import com.logankulinski.jooq.tables.Repository;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.issue</code>.
     */
    public static final Issue ISSUE = Issue.ISSUE;

    /**
     * The table <code>public.label</code>.
     */
    public static final Label LABEL = Label.LABEL;

    /**
     * The table <code>public.repository</code>.
     */
    public static final Repository REPOSITORY = Repository.REPOSITORY;
}
