spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME}
  jooq:
    sql-dialect: ${JOOQ_SQL_DIALECT}
github:
  username: ${GITHUB_USERNAME}
  token: ${GITHUB_TOKEN}
slack:
  token: ${SLACK_TOKEN}
rollbar:
  access-token: ${ROLLBAR_ACCESS_TOKEN}
  environment: ${ROLLBAR_ENVIRONMENT}