/*
 * This file is generated by jOOQ.
 */
package com.logankulinski.jooq.tables;


import com.logankulinski.jooq.Keys;
import com.logankulinski.jooq.Public;
import com.logankulinski.jooq.tables.records.LabelRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Label extends TableImpl<LabelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.label</code>
     */
    public static final Label LABEL = new Label();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LabelRecord> getRecordType() {
        return LabelRecord.class;
    }

    /**
     * The column <code>public.label.id</code>.
     */
    public final TableField<LabelRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.label.name</code>.
     */
    public final TableField<LabelRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(256), this, "");

    private Label(Name alias, Table<LabelRecord> aliased) {
        this(alias, aliased, null);
    }

    private Label(Name alias, Table<LabelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.label</code> table reference
     */
    public Label(String alias) {
        this(DSL.name(alias), LABEL);
    }

    /**
     * Create an aliased <code>public.label</code> table reference
     */
    public Label(Name alias) {
        this(alias, LABEL);
    }

    /**
     * Create a <code>public.label</code> table reference
     */
    public Label() {
        this(DSL.name("label"), null);
    }

    public <O extends Record> Label(Table<O> child, ForeignKey<O, LabelRecord> key) {
        super(child, key, LABEL);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<LabelRecord, Integer> getIdentity() {
        return (Identity<LabelRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<LabelRecord> getPrimaryKey() {
        return Keys.LABEL_PKEY;
    }

    @Override
    public Label as(String alias) {
        return new Label(DSL.name(alias), this);
    }

    @Override
    public Label as(Name alias) {
        return new Label(alias, this);
    }

    @Override
    public Label as(Table<?> alias) {
        return new Label(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Label rename(String name) {
        return new Label(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Label rename(Name name) {
        return new Label(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Label rename(Table<?> name) {
        return new Label(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
