name: Spring Projects First-timer Bot PR CI
on:
  pull_request_target:
    branches: [ "main" ]
jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Setup JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '19'
      - name: Build with Maven
        env:
          DATABASE_DRIVER_CLASS_NAME: ${{ secrets.DATABASE_DRIVER_CLASS_NAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          GITHUB_USERNAME: ${{ secrets.USERNAME_GITHUB }}
          JOOQ_SQL_DIALECT: ${{ secrets.JOOQ_SQL_DIALECT }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: mvn -B package --file pom.xml